baseURL = 'https://inverted-tree.github.io/'
languageCode = 'en-us'
title = "Lukas's Blog"
theme = "archie"
copyright = "© Lukas Schröder — CC BY-NC 4.0 & MIT"

[Author]
name = "Lukas Schröder"

[params]
favicon = "https://img.icons8.com/windows/96/dev.png"
mode = "toggle"
useCDN = true
subtitle = "Any sufficiently advanced technology is indistinguishable from magic. — _Arthur C. Clarke's third law._"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/inverted-tree"

[[params.social]]
name = "RSS"
icon = "rss"
url = "https://inverted-tree.github.io/index.xml"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2
