baseURL = 'https://xn--c1adtlmkl.cc/'
languageCode = 'en-us'
title = "сегфолт.cc [segmentation fault]"
copyright = "Lukas Schröder"

[Author]
name = "Lukas Schröder"

[params]
favicon = "https://img.icons8.com/windows/96/dev.png"
mode = "toggle"
useCDN = true
launchYear = 2025
subtitle = [
    "This is where I yap about my interests."
]
footer = "A CI/CD pipeline for my thoughts. Share this site:"
license = "license"
qrCode = "./img/qr-code.svg"
qrText = "scan for segfault"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/inverted-tree"

[[params.social]]
name = "RSS"
icon = "rss"
url = "https://xn--c1adtlmkl.cc/index.xml"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[module]
  [[module.imports]]
    path = "github.com/inverted-tree/segfault"
